---
title: "Heatmaps"
author: "Tamas Schauer"
date: "15.12.2017"
output:
  html_document: default
  pdf_document: default
geometry: margin=0.9in
font-family: Helvetica
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(cache=TRUE)
```


```{r,message=FALSE,  warning=FALSE}
library(ComplexHeatmap)
library(RColorBrewer)
library(circlize)
library(dendextend)
library(genefilter)
```


## Data Setup

```{r, ,message=FALSE, warning=FALSE}
my_counts <- read.csv("my_counts_GENEnorm_Means.csv", row.names = 1)

log2_norm_counts <- log2(my_counts+1)
log2_norm_counts <- log2_norm_counts[rowMeans(log2_norm_counts) > median(rowMeans(log2_norm_counts)),]

my_order <- order(rowVars(log2_norm_counts))

n_of_genes <- 100

log2_norm_counts <- rbind(head(log2_norm_counts[my_order,],n_of_genes),
                          tail(log2_norm_counts[my_order,],n_of_genes))

my_split <- c(rep("Least Variable",n_of_genes), rep("Most Variable",n_of_genes))

mat1 <- log2_norm_counts
mat2 <- log2_norm_counts - rowMeans(log2_norm_counts)
mat3 <- (log2_norm_counts - rowMeans(log2_norm_counts))/rowSds(log2_norm_counts)
```

\pagebreak




## Heatmap Setup

```{r, message=FALSE, fig.align='center', warning=FALSE}
top_annotation = HeatmapAnnotation(df = data.frame(Stage = c(1,rep(2:8,each=2))),
                                   col = list(Stage = colorRamp2(c(1, 8),c(rgb(0.9,0.9,0.9),rgb(0.2,0.2,0.2)))),
                                   annotation_legend_param = list(color_bar = "discrete", labels=1:8, at=1:8))

heatmap_legend_param = list(legend_direction = "horizontal",
                            legend_width = unit(3,"cm"),
                            title_position = "lefttop")


myHeatmap <- function(mat, column_title, name, split, col, clustering_method_rows = "complete"){
    Heatmap(mat, 
            col = col,
            column_title = column_title,
            name = name,
            show_column_names = FALSE, 
            show_row_names = FALSE, 
            cluster_columns = FALSE,
            cluster_rows = TRUE,
            clustering_method_rows = clustering_method_rows,
            split = my_split, gap = unit(2.5, "mm"),
            top_annotation = top_annotation,
            heatmap_legend_param = heatmap_legend_param
            )
}

color_function <- function(mat){
    x = as.vector(as.matrix(mat))
    colfun <- colorRamp2(breaks = seq(quantile(x, 0.01), quantile(x, 0.99), length = 3), 
                         colors = c("blue", "#EEEEEE", "red"))
    return(colfun)
}

```


## Basic Settings

```{r, message=FALSE, fig.align='center', warning=FALSE}

ht1 <- myHeatmap(mat1, col =  color_function(mat1), name = "(A)", column_title = "(A) Log2 Counts")
ht2 <- myHeatmap(mat2, col =  color_function(mat2), name = "(B)", column_title = "(B) Row Scaled")
ht3 <- myHeatmap(mat3, col =  color_function(mat3), name = "(C)", column_title = "(C) Row Z-Scores")


ht_list = ht1 + ht2 + ht3

draw(ht_list, 
     heatmap_legend_side = "bottom",
     padding = unit(c(0, 0, 0, 3), "cm"))
```


## Color Settings

### Side track on colors

```{r, message=FALSE, fig.align='center', warning=FALSE}
par(mfrow=c(1,6), mar=c(2,2,2,2))

my_brewers <- c("Set1","Greys","Blues","Reds", "RdBu", "RdYlBu")

for(my_brewer in my_brewers){
    image(t(matrix(1:9)), col=brewer.pal(9,my_brewer), main = my_brewer, cex.main=2)
    text(0, seq(0,1,length.out = 9), labels = brewer.pal(9,my_brewer))
}
```

### Change colors

```{r, message=FALSE, fig.align='center', warning=FALSE}

color_function1 <- function(mat){
    x = as.vector(as.matrix(mat))
    colfun <- colorRamp2(breaks = seq(quantile(x, 0.01), quantile(x, 0.99), length = 9), 
                         colors = brewer.pal(9,"Reds"))
    return(colfun)
}


color_function2 <- function(mat){
    x = as.vector(as.matrix(mat))
    colfun <- colorRamp2(breaks = seq(quantile(x, 0.01), quantile(x, 0.99), length = 9), 
                         colors = rev(brewer.pal(9,"RdYlBu")))
    return(colfun)
}


ht1 <- myHeatmap(mat1, col =  color_function1(mat1), name = "(A)", column_title = "(A) Log2 Counts")
ht2 <- myHeatmap(mat2, col =  color_function2(mat2), name = "(B)", column_title = "(B) Row Scaled")
ht3 <- myHeatmap(mat3, col =  color_function2(mat3), name = "(C)", column_title = "(C) Row Z-Scores")


ht_list = ht1 + ht2 + ht3

draw(ht_list, 
     heatmap_legend_side = "bottom",
     padding = unit(c(0, 0, 0, 3), "cm"))
```


### Change contrasts

```{r, message=FALSE, fig.align='center', warning=FALSE}

color_function1 <- function(mat){
    x = as.vector(as.matrix(mat))
    colfun <- colorRamp2(breaks = seq(0, 20, length = 9), 
                         colors = brewer.pal(9,"Reds"))
    return(colfun)
}


color_function2 <- function(mat){
    x = as.vector(as.matrix(mat))
    colfun <- colorRamp2(breaks = seq(-10, 10, length = 9), 
                         colors = rev(brewer.pal(9,"RdYlBu")))
    return(colfun)
}


ht1 <- myHeatmap(mat1, col =  color_function1(mat1), name = "(A)", column_title = "(A) Log2 Counts")
ht2 <- myHeatmap(mat2, col =  color_function2(mat2), name = "(B)", column_title = "(B) Row Scaled")
ht3 <- myHeatmap(mat3, col =  color_function2(mat3), name = "(C)", column_title = "(C) Row Z-Scores")


ht_list = ht1 + ht2 + ht3

draw(ht_list, 
     heatmap_legend_side = "bottom",
     padding = unit(c(0, 0, 0, 3), "cm"))
```



### Change symmetry

```{r, message=FALSE, fig.align='center', warning=FALSE}

color_function2 <- function(mat){
    x = as.vector(as.matrix(mat))
    colfun <- colorRamp2(breaks = seq(-5, 15, length = 9), 
                         colors = rev(brewer.pal(9,"RdBu")))
    return(colfun)
}


ht1 <- myHeatmap(mat1, col =  color_function2(mat1), name = "(A)", column_title = "(A) Log2 Counts")
ht2 <- myHeatmap(mat2, col =  color_function2(mat2), name = "(B)", column_title = "(B) Row Scaled")
ht3 <- myHeatmap(mat3, col =  color_function2(mat3), name = "(C)", column_title = "(C) Row Z-Scores")


ht_list = ht1 + ht2 + ht3

draw(ht_list, 
     heatmap_legend_side = "bottom",
     padding = unit(c(0, 0, 0, 3), "cm"))
```


# Clustering


```{r, echo=FALSE, message=FALSE, fig.align='center', warning=FALSE}
color_function1 <- function(mat){
    x = as.vector(as.matrix(mat))
    colfun <- colorRamp2(breaks = seq(0, 15, length = 9), 
                         colors = brewer.pal(9,"Reds"))
    return(colfun)
}


color_function2 <- function(mat){
    x = as.vector(as.matrix(mat))
    colfun <- colorRamp2(breaks = seq(-5, 5, length = 9), 
                         colors = rev(brewer.pal(9,"RdYlBu")))
    return(colfun)
}

color_function3 <- function(mat){
    x = as.vector(as.matrix(mat))
    colfun <- colorRamp2(breaks = seq(-2, 2, length = 9), 
                         colors = rev(brewer.pal(9,"RdYlBu")))
    return(colfun)
}
```

### Complete

```{r, message=FALSE, fig.align='center', warning=FALSE}

ht1 <- myHeatmap(mat1, col =  color_function1(mat1), name = "(A)", column_title = "(A) Log2 Counts", 
                 clustering_method_rows = "complete")
ht2 <- myHeatmap(mat2, col =  color_function2(mat2), name = "(B)", column_title = "(B) Row Scaled")
ht3 <- myHeatmap(mat3, col =  color_function3(mat3), name = "(C)", column_title = "(C) Row Z-Scores")

ht_list = ht1 + ht2 + ht3

draw(ht_list, heatmap_legend_side = "bottom",padding = unit(c(0, 0, 0, 3), "cm"))
```

### Average

```{r, message=FALSE, fig.align='center', warning=FALSE}

ht1 <- myHeatmap(mat1, col =  color_function1(mat1), name = "(A)", column_title = "(A) Log2 Counts", 
                 clustering_method_rows = "average")
ht2 <- myHeatmap(mat2, col =  color_function2(mat2), name = "(B)", column_title = "(B) Row Scaled")
ht3 <- myHeatmap(mat3, col =  color_function3(mat3), name = "(C)", column_title = "(C) Row Z-Scores")

ht_list = ht1 + ht2 + ht3

draw(ht_list, heatmap_legend_side = "bottom",padding = unit(c(0, 0, 0, 3), "cm"))
```


### ward.D

```{r, message=FALSE, fig.align='center', warning=FALSE}

ht1 <- myHeatmap(mat1, col =  color_function1(mat1), name = "(A)", column_title = "(A) Log2 Counts", 
                 clustering_method_rows = "ward.D")
ht2 <- myHeatmap(mat2, col =  color_function2(mat2), name = "(B)", column_title = "(B) Row Scaled")
ht3 <- myHeatmap(mat3, col =  color_function3(mat3), name = "(C)", column_title = "(C) Row Z-Scores")

ht_list = ht1 + ht2 + ht3

draw(ht_list, heatmap_legend_side = "bottom",padding = unit(c(0, 0, 0, 3), "cm"))
```


